# Generated by Django 5.0.2 on 2025-08-30 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='paymentstatus',
            index=models.Index(fields=['status'], name='payments_pa_status_ca69dc_idx'),
        ),
        migrations.AddIndex(
            model_name='paymentstatus',
            index=models.Index(fields=['is_active'], name='payments_pa_is_acti_6a054d_idx'),
        ),
    ]
