# Generated by Django 5.0.2 on 2026-05-11 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_paymentstatus_payments_pa_status_ca69dc_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentstatus',
            name='code',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
