# Generated by Django 5.0.2 on 2026-01-18 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_remove_user_currency_remove_user_income_frequency_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="currency",
            options={
                "ordering": ["sort_order", "code"],
                "verbose_name_plural": "Currencies",
            },
        ),
        migrations.AddField(
            model_name="currency",
            name="sort_order",
            field=models.IntegerField(default=100),
        ),
    ]
