# Generated by Django 5.0.2 on 2026-01-18 18:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_alter_currency_options_currency_sort_order"),
    ]

    operations = [
        migrations.CreateModel(
            name="IncomeFrequency",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=20, unique=True)),
                ("name", models.CharField(max_length=50)),
                ("description", models.TextField(blank=True)),
                ("sort_order", models.PositiveIntegerField(default=100)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name_plural": "Income Frequencies",
                "ordering": ["sort_order", "name"],
            },
        ),
        migrations.RenameIndex(
            model_name="userprofile",
            new_name="users_userp_income__6fc7a6_idx",
            old_name="users_userp_income__febdd3_idx",
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="income_frequency",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="profiles",
                to="users.incomefrequency",
            ),
        ),
    ]
