# Generated by Django 5.0.2 on 2026-01-24 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_incomefrequency_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="phone",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddIndex(
            model_name="userprofile",
            index=models.Index(fields=["phone"], name="users_userp_phone_ed0c08_idx"),
        ),
    ]
