# Generated by Django 5.0.2 on 2026-01-26 01:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0006_userprofile_first_name_userprofile_last_name"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="name",
        ),
    ]
