# Generated by Django 5.0.2 on 2026-02-13 05:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0007_remove_user_name"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="incomefrequency",
            options={"ordering": ["id"], "verbose_name_plural": "Income Frequencies"},
        ),
        migrations.RemoveField(
            model_name="incomefrequency",
            name="code",
        ),
        migrations.RemoveField(
            model_name="incomefrequency",
            name="sort_order",
        ),
    ]
