# Generated by Django 5.0.2 on 2025-05-22 05:35

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('payments', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name_plural': 'Categories',
                'ordering': ['record_type', 'name'],
            },
        ),
        migrations.CreateModel(
            name='FinancialRecordType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='FinancialRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('description', models.TextField(blank=True)),
                ('record_date', models.DateField()),
                ('is_recurrent', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='finance.category')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_records', to='users.user')),
                ('payment_method', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='payments.paymentmethod')),
                ('payment_status', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='payments.paymentstatus')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='financial_records', to='users.user')),
                ('record_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='finance.financialrecordtype')),
            ],
            options={
                'ordering': ['-record_date', '-created_at'],
            },
        ),
        migrations.AddField(
            model_name='category',
            name='record_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='finance.financialrecordtype'),
        ),
        migrations.CreateModel(
            name='FinancialRecordMetadata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frequency_type', models.CharField(blank=True, choices=[('days', 'Days'), ('weeks', 'Weeks'), ('months', 'Months'), ('years', 'Years')], max_length=10, null=True)),
                ('frequency_value', models.IntegerField(blank=True, null=True)),
                ('next_occurrence', models.DateField(blank=True, null=True)),
                ('extra_notes', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('financial_record', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='finance.financialrecord')),
            ],
            options={
                'ordering': ['-next_occurrence'],
                'indexes': [models.Index(fields=['is_active', 'next_occurrence'], name='finance_fin_is_acti_249b1b_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='financialrecord',
            index=models.Index(fields=['user', 'record_date'], name='finance_fin_user_id_dc46d8_idx'),
        ),
        migrations.AddIndex(
            model_name='financialrecord',
            index=models.Index(fields=['record_type', 'category'], name='finance_fin_record__2d783d_idx'),
        ),
        migrations.AddIndex(
            model_name='financialrecord',
            index=models.Index(fields=['is_recurrent'], name='finance_fin_is_recu_e3e82c_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='category',
            unique_together={('name', 'record_type')},
        ),
    ]
