# Generated by Django 5.0.2 on 2025-06-22 09:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("finance", "0001_initial"),
        ("payments", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="financialrecord",
            name="created_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="created_records",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="financialrecord",
            name="payment_method",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="payments.paymentmethod",
            ),
        ),
        migrations.AddField(
            model_name="financialrecord",
            name="payment_status",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="payments.paymentstatus",
            ),
        ),
        migrations.AddField(
            model_name="financialrecord",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="financial_records",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="financialrecordmetadata",
            name="financial_record",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                to="finance.financialrecord",
            ),
        ),
        migrations.AddField(
            model_name="financialrecord",
            name="record_type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="finance.financialrecordtype",
            ),
        ),
        migrations.AddField(
            model_name="category",
            name="record_type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="finance.financialrecordtype",
            ),
        ),
        migrations.AddIndex(
            model_name="financialrecordmetadata",
            index=models.Index(
                fields=["is_active", "next_occurrence"],
                name="finance_fin_is_acti_249b1b_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="financialrecord",
            index=models.Index(
                fields=["user", "record_date"], name="finance_fin_user_id_dc46d8_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="financialrecord",
            index=models.Index(
                fields=["record_type", "category"],
                name="finance_fin_record__2d783d_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="financialrecord",
            index=models.Index(
                fields=["is_recurrent"], name="finance_fin_is_recu_e3e82c_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="category",
            unique_together={("name", "record_type")},
        ),
    ]
