# Generated by Django 5.0.2 on 2026-02-15 01:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0003_remove_userfinancedashboard_records"),
        ("finance", "0002_initial"),
        ("payments", "0002_paymentstatus_payments_pa_status_ca69dc_idx_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="financialrecord",
            name="dashboard",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="financial_records",
                to="dashboard.userfinancedashboard",
            ),
        ),
        migrations.AddIndex(
            model_name="financialrecord",
            index=models.Index(
                fields=["dashboard"], name="finance_fin_dashboa_125efb_idx"
            ),
        ),
    ]
