# Generated by Django 5.0.2 on 2026-02-21 01:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finance", "0004_fill_dashboard_and_set_not_null"),
        ("users", "0009_add_currency_sort_order_column"),
    ]

    operations = [
        migrations.AddField(
            model_name="financialrecordmetadata",
            name="currency",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="users.currency",
            ),
        ),
    ]
