# Generated by Django 5.0.2 on 2026-05-11 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0005_financialrecordmetadata_currency'),
    ]

    operations = [
        migrations.AddField(
            model_name='financialrecordtype',
            name='behavior',
            field=models.CharField(choices=[('INCOME', 'Income'), ('EXPENSE', 'Expense'), ('TRANSFER', 'Transfer')], default='EXPENSE', max_length=20),
        ),
    ]
