# Generated by Django 5.0.2 on 2026-05-11 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0006_financialrecordtype_behavior'),
    ]

    operations = [
        migrations.AddField(
            model_name='financialrecord',
            name='current_installment',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='financialrecord',
            name='total_installments',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
