# Generated by Django 5.0.2 on 2026-05-12 03:50

from django.db import migrations

def create_initial_record_types(apps, schema_editor):
    FinancialRecordType = apps.get_model('finance', 'FinancialRecordType')
    # Use get_or_create to avoid duplicates if they already exist
    FinancialRecordType.objects.get_or_create(
        name='expense', 
        defaults={'behavior': 'EXPENSE', 'description': 'Gastos generales'}
    )
    FinancialRecordType.objects.get_or_create(
        name='income', 
        defaults={'behavior': 'INCOME', 'description': 'Ingresos generales'}
    )

def remove_initial_record_types(apps, schema_editor):
    FinancialRecordType = apps.get_model('finance', 'FinancialRecordType')
    FinancialRecordType.objects.filter(name__in=['expense', 'income']).delete()

class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0007_financialrecord_current_installment_and_more'),
    ]

    operations = [
        migrations.RunPython(create_initial_record_types, remove_initial_record_types),
    ]
