# Generated by Django 5.0.2 on 2026-05-12 04:00

from django.db import migrations

def create_initial_categories(apps, schema_editor):
    Category = apps.get_model('finance', 'Category')
    FinancialRecordType = apps.get_model('finance', 'FinancialRecordType')

    # Ensure types exist just in case
    expense_type, _ = FinancialRecordType.objects.get_or_create(name='expense', defaults={'behavior': 'EXPENSE'})
    income_type, _ = FinancialRecordType.objects.get_or_create(name='income', defaults={'behavior': 'INCOME'})

    expense_categories = [
        'Comida', 'Transporte', 'Vivienda', 'Internet', 'Streaming', 
        'Salud', 'Servicios', 'Gasolina', 'Tarjetas', 'Entretenimiento'
    ]
    
    income_categories = [
        'Sueldo', 'Freelance', 'Bonos', 'Ventas', 'Reembolsos', 'Negocio'
    ]

    for cat_name in expense_categories:
        Category.objects.get_or_create(name=cat_name, record_type=expense_type)

    for cat_name in income_categories:
        Category.objects.get_or_create(name=cat_name, record_type=income_type)

def remove_initial_categories(apps, schema_editor):
    Category = apps.get_model('finance', 'Category')
    Category.objects.filter(
        name__in=[
            'Comida', 'Transporte', 'Vivienda', 'Internet', 'Streaming', 
            'Salud', 'Servicios', 'Gasolina', 'Tarjetas', 'Entretenimiento',
            'Sueldo', 'Freelance', 'Bonos', 'Ventas', 'Reembolsos', 'Negocio'
        ]
    ).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0008_auto_20260511_2150'),
    ]

    operations = [
        migrations.RunPython(create_initial_categories, remove_initial_categories),
    ]
