# Generated by Django 5.0.2 on 2026-05-17 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finance", "0009_auto_20260511_2200"),
    ]

    operations = [
        migrations.AddField(
            model_name="financialrecord",
            name="is_active",
            field=models.BooleanField(db_index=True, default=True),
        ),
    ]
