# Generated by Django 5.0.2 on 2026-05-28 00:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0010_financialrecord_is_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryKeyword',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.CharField(max_length=100)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='keywords', to='finance.category')),
            ],
            options={
                'ordering': ['category', 'keyword'],
                'unique_together': {('category', 'keyword')},
            },
        ),
    ]
