# Generated by Django 5.0.2 on 2026-05-28 00:44

from django.db import migrations


def seed_keywords(apps, schema_editor):
    Category = apps.get_model('finance', 'Category')
    CategoryKeyword = apps.get_model('finance', 'CategoryKeyword')
    FinancialRecordType = apps.get_model('finance', 'FinancialRecordType')

    # Get expense record type
    expense_type, _ = FinancialRecordType.objects.get_or_create(name='expense', defaults={'behavior': 'EXPENSE'})

    # Categories and keywords to create
    data = {
        'Telefonía': ['telcel', 'movistar', 'at&t', 'telmex', 'unefon'],
        'Suscripciones': ['spotify', 'netflix', 'prime', 'disney', 'hbo', 'apple.com/bill', 'youtube premium'],
        'Transporte': ['uber', 'didi', 'cabify', 'indrive', 'taxi', 'boleto'],
        'Salud': ['farmacia', 'doctor', 'consultorio', 'hospital', 'guadalajara', 'similares', 'dentista', 'medico']
    }

    for cat_name, keywords in data.items():
        category, _ = Category.objects.get_or_create(name=cat_name, record_type=expense_type)
        for kw in keywords:
            # We strip and lowercase to match clean logic
            kw_clean = kw.strip().lower()
            CategoryKeyword.objects.get_or_create(category=category, keyword=kw_clean)


def remove_keywords(apps, schema_editor):
    CategoryKeyword = apps.get_model('finance', 'CategoryKeyword')
    CategoryKeyword.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0011_categorykeyword'),
    ]

    operations = [
        migrations.RunPython(seed_keywords, remove_keywords),
    ]
