# Generated by Django 5.0.2 on 2026-08-28 08:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finance", "0013_financialgoal"),
    ]

    operations = [
        migrations.AddField(
            model_name="financialrecord",
            name="financial_goal",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="linked_records",
                to="finance.financialgoal",
            ),
        ),
    ]
