# Generated by Django 5.0.2 on 2026-02-15 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0001_initial"),
        ("finance", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="userfinancedashboard",
            name="records",
            field=models.ManyToManyField(
                blank=True, related_name="dashboards", to="finance.financialrecord"
            ),
        ),
    ]
