# Generated by Django 5.0.2 on 2026-02-15 01:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0002_userfinancedashboard_records"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userfinancedashboard",
            name="records",
        ),
    ]
