# Generated by Django 5.0.2 on 2026-02-15 01:40

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0003_remove_userfinancedashboard_records"),
        ("users", "0008_alter_incomefrequency_options_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="userfinancedashboard",
            options={"ordering": ["-updated_at"]},
        ),
        migrations.RemoveIndex(
            model_name="userfinancedashboard",
            name="dashboard_u_user_id_b00faf_idx",
        ),
        migrations.AlterUniqueTogether(
            name="userfinancedashboard",
            unique_together=set(),
        ),
        migrations.AddIndex(
            model_name="userfinancedashboard",
            index=models.Index(fields=["user"], name="dashboard_u_user_id_7ebcfb_idx"),
        ),
        migrations.RemoveField(
            model_name="userfinancedashboard",
            name="balance",
        ),
        migrations.RemoveField(
            model_name="userfinancedashboard",
            name="period_start",
        ),
        migrations.RemoveField(
            model_name="userfinancedashboard",
            name="period_type",
        ),
        migrations.RemoveField(
            model_name="userfinancedashboard",
            name="total_expense",
        ),
        migrations.RemoveField(
            model_name="userfinancedashboard",
            name="total_income",
        ),
    ]
