# Generated by Django 5.0.2 on 2026-02-19 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0004_alter_userfinancedashboard_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="userfinancedashboard",
            name="description",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="userfinancedashboard",
            name="name",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
    ]
