# Generated by Django 5.0.2 on 2026-05-11 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_userfinancedashboard_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userfinancedashboard',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
