# Generated by Django 5.0.2 on 2026-05-17 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0006_userfinancedashboard_created_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="userfinancedashboard",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
    ]
