# Generated by Django 5.0.2 on 2026-06-07 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_userfinancedashboard_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='userfinancedashboard',
            name='dashboard_type',
            field=models.CharField(choices=[('EXPENSES', 'Expenses'), ('INCOME', 'Income'), ('BOTH', 'Both')], default='BOTH', max_length=10),
        ),
    ]
