# Generated by Django 5.0.2 on 2026-09-12 20:21

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0008_userfinancedashboard_dashboard_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='userfinancedashboard',
            name='monthly_budget',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Límite o presupuesto mensual asignado específicamente a este dashboard/tarjeta.', max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
    ]
